// Random value generated by Computer
const computerPlay = () => {
  let randomNumber = Math.floor(Math.random() * 3);
  if (randomNumber === 0) {
    return "rock";
  } else if (randomNumber === 1) {
    return "paper";
  } else {
    return "scissors";
  }
};

// Round played between playerSelection and computerSelection

const playRound = (playerSelection, computerSelection) => {
  if (playerSelection === "rock") {
    if (computerSelection === "paper") {
      return `You Lose! ${playerSelection} gets wrapped  by ${computerSelection}`;
    } else if (computerSelection === "scissors") {
      return `You Win! ${playerSelection} breaks ${computerSelection}`;
    } else {
      return `It's a draw! `;
    }
  } else if (playerSelection === "paper") {
    if (computerSelection === "rock") {
      return `You Win! ${playerSelection}  wraps  ${computerSelection}`;
    } else if (computerSelection === "scissors") {
      return `You Lose! ${playerSelection} gets cut by ${computerSelection}`;
    } else {
      return `It's a draw! `;
    }
  } else if (playerSelection === "scissors") {
    if (computerSelection === "rock") {
      return `You Lose! ${playerSelection} is broken by ${computerSelection}`;
    } else if (computerSelection === "paper") {
      return `You Win! ${playerSelection} cuts ${computerSelection}`;
    } else {
      return `It's a draw! `;
    }
  }
};

const game = () => {
  let playerScore = 0;
  let computerScore = 0;

  const playMessage = document.querySelector("#play-area");
  playMessage.innerHTML = `<h2> <h2><h3>Choose from Rock paper and scissors</h3>
    <button id="rock" class="value">Rock</button>
   <button id="paper" class="value">Paper</button>
    <button id="scissors" class="value">Scissors</button>`;

  // var td;
  // for (var t = 1; t < 8; t++){
  //     td = document.getElementById('td'+t);
  //     if (typeof window.addEventListener === 'function'){
  //         (function (_td) {
  //             td.addEventListener('click', function(){
  //                 console.log(_td);
  //             });
  //         })(td);
  //     }
  // }

  const playerSelection = document.querySelectorAll(".value");
  playerSelection.forEach(function (selection) {
    selection.addEventListener("click", function () {
      if (selection === playerSelection[0]) {
        const playerSelection = selection.id;
        const computerSelection = computerPlay();
        const displayMessage = playRound(playerSelection, computerSelection);
        const displayMessageArray = displayMessage.split(" ");

        if (displayMessageArray[1] === "Win!") {
          playerScore++;
        } else if (displayMessageArray[1] === "Lose!") {
          computerScore++;
        }
        playMessage.innerHTML += `<h2>${displayMessage}</h2>
                                  <h3>YOU:${playerScore} | Comp: ${computerScore}</h3> `;
      } else if (selection === playerSelection[1]) {
        const playerSelection = selection.id;
        const computerSelection = computerPlay();
        const displayMessage = playRound(playerSelection, computerSelection);
        playMessage.innerHTML += `<h2>${displayMessage}</h2>`;
      } else {
        const playerSelection = selection.id;
        const computerSelection = computerPlay();
        const displayMessage = playRound(playerSelection, computerSelection);
        playMessage.innerHTML += `<h2>${displayMessage}</h2>`;
      }
    });
  });
};

const playGame = document.querySelector("#play-game");

const startGame = playGame.addEventListener("click", game);
