let computerSelection;
let playerSelection;
const playArea = document.getElementById('play-area');
const playerChoice = document.querySelectorAll('.value');
const displayResult = document.querySelector('.display-result');
const playerCounter = document.querySelector('.player-counter');
const computerCounter = document.querySelector('.computer-counter');
const main = document.querySelector('#main');

let playerScore = 0;
let computerScore = 0;
let drawScore = 0;

// player Selection
playerChoice.forEach((choice) => {
  choice.addEventListener('click', function (e) {
    playerSelection = e.target.id;
    computerSelection = computerPlay();
    // console.log(playerSelection);

    let result = getResult(playerSelection, computerSelection);
    console.log('me '+playerSelection);
    console.log('comp '+computerSelection);

    // Displays the selection
    displayResult.innerHTML = `<p>Computer Selected: <span> ${computerSelection}<span></p><p> You Selected: <span> ${playerSelection}</span></p> 
      <h3>${result}</h3><br><br>`;

    // Score Counter
    if (result === 'You Win') {
      playerScore++;
    } else if (result === 'You Lose') {
      computerScore++;
    } else if (result === 'Its a draw') {
      drawScore++;
    }

    // Result after 5 rounds
    if (playerScore + computerScore + drawScore === 5) {
      if (playerScore > computerScore) {
        main.innerHTML = `<h2>YOU WIN THE GAME</h2>`;
      } else if (computerScore > playerScore) {
        main.innerHTML = `<h2>YOU LOSE THE GAME</h2>`;
      }else if(drawScore === 5) {
        main.innerHTML = `<h2>ITS A DRAW</h2>`;

      }
    }

    playerCounter.innerHTML = `<p>Your Score: <span>${playerScore}</span></p>`;
    computerCounter.innerHTML = `<p>Computer Score: <span>${computerScore}</span></p>`;
  });
});

//computer selection
// Random value generated by Computer
function computerPlay() {
  let randomNumber = Math.floor(Math.random() * 3);
  if (randomNumber === 0) {
    return 'rock';
  } else if (randomNumber === 1) {
    return 'paper';
  } else {
    return 'scissors';
  }
}

// Get Results
function getResult(player, computer) {
  if (player === computer) {
    return 'Its a draw';
  } else if (player === 'rock' && computer === 'paper') {
    return 'You Lose';
  } else if (player === 'rock' && computer === 'scissors') {
    return 'You Win';
  } else if (player === 'paper' && computer === 'rock') {
    return 'You Win';
  } else if (player === 'paper' && computer === 'scissors') {
    return 'You Lose';
  } else if (player === 'scissors' && computer === 'rock') {
    return 'You Lose';
  } else if (player === 'scissors' && computer === 'paper') {
    return 'You Win';
  }
}
